### Testing to see if removing Bwd Flow Data will improve the performance of the model

In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from imblearn.ensemble import BalancedRandomForestClassifier
from imblearn.ensemble import EasyEnsembleClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import RandomizedSearchCV

In [7]:
data = pd.read_csv('/Users/sa12/Documents/Repositories/The-CyberChase/DATA/CleanNoBwd')
data = data.drop(columns='Unnamed: 0')

In [8]:
X = data.drop(columns=['Country'])
y = data['Country']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [9]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
log_model = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=1000,
    random_state=42
)
log_model.fit(X_train_scaled, y_train)
log_pred = log_model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, log_pred))
print("\nClassification Report:\n", classification_report(y_test, log_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, log_pred))

Accuracy: 0.5879802036034109


/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Classification Report:
               precision    recall  f1-score   support

           1       0.82      1.00      0.90    106345
           2       0.39      0.74      0.51     66113
           3       0.19      0.05      0.08     38166
           4       0.57      0.71      0.63     34184
           5       0.00      0.00      0.00     17457
           6       0.24      0.00      0.00     15483
           7       0.00      0.00      0.00      9506
           8       0.00      0.00      0.00      7749
           9       0.00      0.00      0.00      7023
          10       0.00      0.00      0.00      6515

    accuracy                           0.59    308541
   macro avg       0.22      0.25      0.21    308541
weighted avg       0.46      0.59      0.50    308541


Confusion Matrix:
 [[106185    144      0     16      0      0      0      0      0      0]
 [  9852  48851   1488   5911      1      9      0      1      0      0]
 [  1965  27355   1934   6893      0     19      0

/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [11]:
rf_model = BalancedRandomForestClassifier(n_estimators=100, bootstrap=False, random_state=42, replacement=True)
rf_model.fit(X_train_scaled, y_train)
rf_pred = rf_model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, rf_pred))
print("\nClassification Report:\n", classification_report(y_test, rf_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, rf_pred))

/opt/anaconda3/lib/python3.12/site-packages/imblearn/ensemble/_forest.py:577: FutureWarning: The default of `sampling_strategy` will change from `'auto'` to `'all'` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `'all'` to silence this warning and adopt the future behaviour.
  warn(


Accuracy: 0.7598957674992951

Classification Report:
               precision    recall  f1-score   support

           1       0.94      0.91      0.92    106345
           2       0.72      0.52      0.61     66113
           3       0.60      0.69      0.64     38166
           4       0.91      0.84      0.88     34184
           5       0.67      0.72      0.69     17457
           6       0.54      0.66      0.60     15483
           7       0.53      0.88      0.66      9506
           8       0.69      0.74      0.71      7749
           9       0.82      0.89      0.85      7023
          10       0.39      0.70      0.50      6515

    accuracy                           0.76    308541
   macro avg       0.68      0.76      0.71    308541
weighted avg       0.78      0.76      0.76    308541


Confusion Matrix:
 [[97078   914     6     0  1737    16  3571    62     5  2956]
 [ 3704 34612 14056  1622  1413  3432  3758  1012   501  2003]
 [ 1259  1734 26297   805  2575  3543   1

In [12]:
EE_model = EasyEnsembleClassifier(n_estimators=10, random_state=42)
EE_model.fit(X_train_scaled, y_train)
EE_pred = EE_model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, EE_pred))
print("\nClassification Report:\n", classification_report(y_test, EE_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, EE_pred))

Accuracy: 0.5685468057729767

Classification Report:
               precision    recall  f1-score   support

           1       0.83      1.00      0.91    106345
           2       0.35      0.03      0.05     66113
           3       0.45      0.56      0.50     38166
           4       0.46      0.77      0.58     34184
           5       0.32      0.44      0.37     17457
           6       0.26      0.35      0.30     15483
           7       0.43      0.16      0.24      9506
           8       0.08      0.15      0.11      7749
           9       0.60      0.56      0.58      7023
          10       0.12      0.03      0.04      6515

    accuracy                           0.57    308541
   macro avg       0.39      0.40      0.37    308541
weighted avg       0.53      0.57      0.51    308541


Confusion Matrix:
 [[106217      0      0    101      2      0      7     15      3      0]
 [ 10947   1785  16060  18932   4221   6286   1056   5264   1332    230]
 [  3067    984  2124

### While there is a very slight increase in the RF model, the other 2 models suffered meaning we will retain that data